<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBJW05hq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBJW05hq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBJW05hq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBJW05hq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBJW05hq\App_KernelDevDebugContainer([
    'container.build_hash' => 'BJW05hq',
    'container.build_id' => '68b64035',
    'container.build_time' => 1648906660,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBJW05hq');
